sudo: false
language: scala

scala:
- 2.12.8

jdk:
- oraclejdk8

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.coursier/cache

before_install:
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt coverage "++$TRAVIS_SCALA_VERSION test" 
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "++$TRAVIS_SCALA_VERSION coverageReport" coverageAggregate codacyCoverage
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test $TRAVIS_REPO_SLUG == "monadplus/equality" && sbt
  ++$TRAVIS_SCALA_VERSION publish && sbt docs/publishMicrosite