sudo: false
language: scala

scala:
- 2.12.8

jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

jobs:
  include:
  - stage: verify

    script:
    - sbt ++$TRAVIS_SCALA_VERSION test
